[package]
name = "advent-of-code-day1-part1"
version = "0.1.0"
authors = ["Edgar León <edgar.leon@icontainers.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
